### ISSUE TITLE
Unnecessary Id's for images

### ISSUE THREAD

**Issue by Aliyss** [davidseibert/docxperiments#5]
Hi. First of all thanks a bunch.

This documentation helped me out quite a bit today.

Additionally: The following attributes within the anchor are unnecessary. I found them when adding an image to the document.
```xml
<wp:anchor wp14:anchorId="3B3E0332" wp14:editId="1E4423CF">
```

**Comment by davidseibert** [comment]
Hey thanks! I had completely forgotten about this. I'm not in a position to carry it forward, so, if you're on this path, feel free to take it over.

**Comment by Aliyss** [comment]
Hey david, thanks for the info. I would love to take over. Do you have a guide or some tips on how you proceeded when taking notes and making changes. Because in general I'm quite good at finding things, but not so much in the documentation part.

**Comment by davidseibert** [comment]
Hi Alyiss! So sorry for the slow responses. Basically, I just started with the blank document (so the XML would be as simple as possible) and made the most minimal edits I could. Then just keep a running list of the new tags that show up in the XML for the edited file. Once you have a theory about how something works, try to reverse the process by manually writing an edit in the XML and seeing if it the reverse-engineered DOCX (1) opens at all and (2) looks the way you predicted.

**Comment by Aliyss** [comment]
@davidseibert

I already came to understand all the objects... Indeed a very slow response ^^. Am currently trying to use it for a private project of mine. It's all in JS though. I am trying to automate the testing or at least make it easier.
